# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: TheR7angelo.MyExpenses
PackageVersion: 1.1.9
InstallerType: exe
InstallerSwitches:
  Silent: /quiet
  SilentWithProgress: /passive
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/TheR7angelo/MyExpenses/releases/download/v1.1.9/MyExepensesUserSetup.x64.exe
  InstallerSha256: 47B68C17630A41B14A8C83F2894C02BC34F246D0BF4AAB781450737A96F1485E
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-04-01
